'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type N0fButtonCustomEvent } from "@n0f/web-components";
import { N0fButton as N0fButtonElement, defineCustomElement as defineN0fButton } from "@n0f/web-components/dist/components/n0f-button.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type N0fButtonEvents = { onN0fClick: EventName<N0fButtonCustomEvent<MouseEvent>> };

export const N0fButton: StencilReactComponent<N0fButtonElement, N0fButtonEvents> = /*@__PURE__*/ createComponent<N0fButtonElement, N0fButtonEvents>({
    tagName: 'n0f-button',
    elementClass: N0fButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onN0fClick: 'n0fClick' } as N0fButtonEvents,
    defineCustomElement: defineN0fButton
});
